var express = require('express');
var router = express.Router();

const itemList = [
  { 'id': 1, 'term': 'DevOps', 'description': 'DevOps, which stands for development and operations, is a set of practices and technologies that aim to improve an organizations capacity to produce applications and services more quickly than traditional software development procedures. ', 'reference': '“What Is DevOps and How Does It Work? | Synopsys,” www.synopsys.com. https://www.synopsys.com/glossary/what-is-devops.html' },
  { 'id': 2, 'term': 'Continuous Integration', 'description': 'Continuous integration developers commit their code changes to a centralized repository on a regular basis, following which automated builds and tests are done.', 'reference': '“What is Continuous Integration? – Amazon Web Services,” Amazon Web Services, Inc. https://aws.amazon.com/devops/continuous-integration/' },
  { 'id': 3, 'term': 'Continuous Deployment', 'description': 'Continuous deployment is a completely developed and comprehensive code change process cycle that goes through every phase of the software life cycle before being delivered to production settings. Automated incremental changes are done as a part of this.', 'reference': 'S. Vadapalli, DevOps: Continuous Delivery, Integration, and Deployment with DevOps: Dive into the core DevOps strategies. Packt Publishing Ltd, 2018.' },
  { 'id': 4, 'term': 'Microservice', 'description': 'A microservice is a small, self-contained software operation that can be deployed and maintained independently.', 'reference': 'A. K. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform: A project-based guide. 2021. [Online]. Available: https://discovery.ebsco.com/linkprocessor/plink?id=db0e7980-bdfb-3d3b-b4e9-127c44a7aebb' },
  { 'id': 5, 'term': 'Shorter Lead Time', 'description': 'It is the time required to get from committing code to successfully executing code in production.', 'reference': 'D. DeBellis and C. Peters, “DORA 2022 Accelerate State of DevOps Report now out,” Google Cloud Blog, Sep. 28, 2022. https://cloud.google.com/blog/products/devops-sre/dora-2022-accelerate-state-of-devops-report-now-out' },
  { 'id': 6, 'term': 'Bootstrap', 'description': 'Bootstrap is the most widely used HTML, CSS, and JS framework for creating a responsive and mobile-friendly website. It can also utilise JavaScript plug-ins.', 'reference': '“What is Bootstrap.” https://www.w3schools.com/whatis/whatis_bootstrap.asp' },
  { 'id': 7, 'term': 'Docker', 'description': 'Docker is a tool that is used to package and publish microservices.', 'reference': 'A. K. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform: A project-based guide. 2021. [Online]. Available: https://discovery.ebsco.com/linkprocessor/plink?id=db0e7980-bdfb-3d3b-b4e9-127c44a7aebb' },
  { 'id': 8, 'term': 'Kubernetes', 'description': 'Kubernetes is a container-based application management platform. It can manage and automate container deployment and scaling. ', 'reference': 'A. K. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform: A project-based guide. 2021. [Online]. Available: https://discovery.ebsco.com/linkprocessor/plink?id=db0e7980-bdfb-3d3b-b4e9-127c44a7aebb' },
  { 'id': 9, 'term': 'Deployment Frequency', 'description': 'The frequency with which software is deployed in a company. ', 'reference': 'D. DeBellis and C. Peters, “DORA 2022 Accelerate State of DevOps Report now out,” Google Cloud Blog, Sep. 28, 2022. https://cloud.google.com/blog/products/devops-sre/dora-2022-accelerate-state-of-devops-report-now-out' },
  { 'id': 10, 'term': 'Recovery Time', 'description': 'The time it takes to repair a service or program that has malfunctioned or gone down. ', 'reference': 'D. DeBellis and C. Peters, “DORA 2022 Accelerate State of DevOps Report now out,” Google Cloud Blog, Sep. 28, 2022. https://cloud.google.com/blog/products/devops-sre/dora-2022-accelerate-state-of-devops-report-now-out' },
  { 'id': 11, 'term': 'Preprod', 'description': 'It is the process by which an organisation prepares the environment and infrastructure for each release by testing apps prior to deployment to production.  It simulates the production environment, where various features are tested before they are delivered to customers.', 'reference': 'Enov, “Preprod Done Right: the Definitive Guide,” Enov8, Feb. 2023, [Online]. Available: https://www.enov8.com/blog/preprod-done-right-the-definitive-guide/' },
  { 'id': 12, 'term': 'Source Code Management', 'description': 'It is a software that is used to track changes to a source code repository. It stores and tracks all the changes that are made to code, documents, etc.', 'reference': 'Atlassian, “Source Code Management | Atlassian Git Tutorial,” Atlassian. https://www.atlassian.com/git/tutorials/source-code-management' },
  { 'id': 13, 'term': 'DevSecOps', 'description': 'It stands for development, security, and operations. The notion of incorporating security practices into the DevOps process is known as DevSecOps. DevSecOps entails fostering a culture of Security as Code through continual, flexible cooperation between release engineers and security teams.', 'reference': '“What is DevSecOps?” https://www.redhat.com/en/topics/devops/what-is-devsecops' },
  { 'id': 14, 'term': 'Docker Image', 'description': 'It is a file which is used to execute code in a docker container.', 'reference': 'A. S. Gillis, “Docker image,” IT Operations, May 2021, [Online]. Available: https://www.techtarget.com/searchitoperations/definition/Docker-image' },
  { 'id': 15, 'term': 'Release Management', 'description': 'It is the process of planning, creating, scheduling, testing, delivering, and controlling software releases ', 'reference': '“What is Release Management? | OpenText.” https://www.microfocus.com/en-us/what-is/release-management' },
  { 'id': 16, 'term': 'Scrum', 'description': 'Scrum is an agile project management framework that uses a set of values, principles, and practises to help teams structure and manage their work. It employs time-boxed development cycles.', 'reference': 'Atlassian, “What is Scrum?,” Atlassian. [Online]. Available: https://www.atlassian.com/agile/scrum' },
  { 'id': 17, 'term': 'Acceptance Testing', 'description': 'Process for determining how well an application meets the approval of end users.', 'reference': 'Jeroen Mulder, Enterprise DevOps for Architects [e-book]. PacktPublishing,2021. Available:https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/' },
  { 'id': 18, 'term': 'Regression Testing', 'description': 'The testing of a software application to see if any recent modifications have had an unfavorable effect on any functionality that were previously in existence. ', 'reference': 'Jeroen Mulder, Enterprise DevOps for Architects [e-book]. PacktPublishing,2021. Available:https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/' },
  { 'id': 19, 'term': 'Agile', 'description': 'Agile project management is based on iterative and collaborative development.', 'reference': 'Coursera, “What is agile? and when to use it,” Coursera, Jul. 2023, [Online]. Available: https://www.coursera.org/articles/what-is-agile-a-beginners-guide' },
  { 'id': 20, 'term': 'Infrastructure as Code', 'description': 'Infrastructure as Code is a piece of code that is responsible for building linked cloud resources known as infrastructure on top of which an application may operate. IaC aids in the automated deployment of infrastructure. ', 'reference': 'Jeroen Mulder, Enterprise DevOps for Architects [e-book]. PacktPublishing,2021. Available:https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/' },
  { 'id': 21, 'term': 'Docker-compose ', 'description': 'It is a container orchestration tool for defining and sharing multi-container applications.  You may provide the services, networks, and volumes required by your application in a single file called docker-compose.yml.', 'reference': '“‘Docker Compose overview,’” Docker Documentation, Aug. 30, 2023. https://docs.docker.com/compose/' },
  { 'id': 22, 'term': 'Azure storage account ', 'description': 'A storage space on Microsoft azure cloud which can be used to store data. It contains data objects such as blobs, files, queues, and tables. ', 'reference': 'Akashdubey-Ms, “Storage account overview - Azure Storage,” Microsoft Learn, Aug. 15, 2023. https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview' },
  { 'id': 23, 'term': 'Container registry ', 'description': 'It is a  repository where docker images are stored.', 'reference': '“What is a container registry?” https://www.redhat.com/en/topics/cloud-native-apps/what-is-a-container-registry' },
  { 'id': 24, 'term': 'Yaml', 'description': 'YAML is a data serialisation language for all computer languages that is user-friendly. It is often used for configuration files and in programmes that store or send data.', 'reference': '“What is YAML?” https://www.redhat.com/en/topics/automation/what-is-yaml' },
  { 'id': 25, 'term': 'Dockerfile', 'description': 'It is a file that contains all of the instructions that the user needs to run on the command line in order to construct an image.', 'reference': 'S. Afreen, “What is a Dockerfile? A Step-by-Step Guide [2023 Updated],” Simplilearn.com, Mar. 2023, [Online]. Available: https://www.simplilearn.com/tutorials/docker-tutorial/what-is-dockerfile' },
  { 'id': 26, 'term': 'MongoDB', 'description': 'MongoDB is a free and open source NoSQL database management system.  It is used to store large amounts of data.', 'reference': 'A. S. Gillis and B. Botelho, “MongoDB,” Data Management, Mar. 2023, [Online]. Available: https://www.techtarget.com/searchdatamanagement/definition/MongoDB' },
  { 'id': 27, 'term': 'Azure Resource Group', 'description': 'It is a container that contains Azure-related resources. ', 'reference': 'Tfitzmac, “Manage resource groups - Azure portal - Azure Resource Manager,” Microsoft Learn, Aug. 16, 2023. https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal' },
  { 'id': 28, 'term': 'SDK', 'description': 'A Software Development Kit is a collection of platform-specific tools used to construct applications for developers in a single location.', 'reference': '“What is SDK? - SDK Explained - AWS,” Amazon Web Services, Inc. https://aws.amazon.com/what-is/sdk/' },
  { 'id': 29, 'term': 'Telemetry', 'description': 'Telemetry is a subset of monitoring that refers to the technique used to describe measurement data from a monitoring tool. Telemetry may be thought of as agents that can be configured to collect particular monitoring data.', 'reference': 'Muhammad Raza (October 14,2021). Explained: Monitoring & Telemetry in DevOps [Website]. Available: https://www.bmc.com/blogs/devops-monitoringtelemetry/' },
  { 'id': 30, 'term': 'Docker swarm ', 'description': 'A container orchestration solution capable of operating thousands of containers at the same time. It is used to manage a Docker daemon cluster.', 'reference': '“‘Swarm mode overview,’” Docker Documentation, Aug. 22, 2023. https://docs.docker.com/engine/swarm/' },
  { 'id': 31, 'term': 'Terraform', 'description': 'Terraform uses application programming interfaces (APIs) to construct and manage resources on cloud platforms and other services. ', 'reference': '“What is Terraform | Terraform | HashiCorp Developer,” What Is Terraform | Terraform | HashiCorp Developer. https://developer.hashicorp.com/terraform/intro' },
  { 'id': 32, 'term': 'Prometheus', 'description': 'Monitoring tool that can successfully gather data and store it using a unique identification. It is in charge of gathering measurements that can be transformed into relevant Grafana visualisations. ', 'reference': 'D. Berman, “Grafana & Prometheus: a match made in heaven?,” Logz.io, Dec. 24, 2019. https://logz.io/blog/prometheus-and-grafana-a-match-made-in-heaven/' },
  { 'id': 33, 'term': 'Grafana', 'description': 'Monitoring tool that allows you to create dashboards that display data as metrics, as well as providing alerting and data insights. Grafana alerts can display with Prometheus alerts.', 'reference': 'D. Berman, “Grafana & Prometheus: a match made in heaven?,” Logz.io, Dec. 24, 2019. https://logz.io/blog/prometheus-and-grafana-a-match-made-in-heaven/' },
  { 'id': 34, 'term': 'Splunk', 'description': 'Splunk is a tool for monitoring and searching through large amounts of data.It indexes and connects information in a searchable container. It can also provide warnings, reports, and visualisations.', 'reference': '“Splunk Data Analytics: Splunk Enterprise or Splunk Hunk?- Cloudian,” Cloudian, Jun. 22, 2023. https://cloudian.com/guides/splunk-big-data/splunk-data-analytics-splunk-enterprise-or-splunk-hunk/' },
  { 'id': 35, 'term': 'Helm', 'description': 'Helm is a tool for defining, installing, and upgrading Kubernetes applications.', 'reference': '“Helm | Helm.” https://helm.sh/' },
  { 'id': 36, 'term': 'Ansible', 'description': 'Ansible is a tool for configuration management and automation. It facilitates application deployment.', 'reference': '“Ansible and How Does it Work,” Spiceworks, Jul. 15, 2022. https://www.spiceworks.com/tech/devops/articles/what-is-ansible/' },
  { 'id': 37, 'term': 'HashiCorp', 'description': 'HashiCorp is a software firm that delivers DevOps infrastructure provisioning and management technologies in a modular fashion. Hashicorp solutions facilitate IT cooperation and automation. ', 'reference': 'A. S. Gillis, “HashiCorp,” IT Operations, Jan. 2019, [Online]. Available: https://www.techtarget.com/searchitoperations/definition/HashiCorp-Atlas' },
  { 'id': 38, 'term': 'Jest', 'description': 'Jest is a JavaScript testing framework that ensures the integrity of any JavaScript codebase. Jest is built on top of Jasmine.', 'reference': '“Jest.” https://jestjs.io/' },
  { 'id': 39, 'term': 'Kubelet', 'description': 'The principal "node agent" that runs on each node is the kubelet. It is capable of registering the node with the apiserver.', 'reference': '“kubelet,” Kubernetes, Aug. 18, 2023. https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/' },
  { 'id': 40, 'term': 'Pod', 'description': 'Pods are the smallest deployable computing units that Kubernetes can build and manage. It can accommodate one or more containers.', 'reference': '“Pods,” Kubernetes. https://kubernetes.io/docs/concepts/workloads/pods' },
  { 'id': 41, 'term': 'CaaS', 'description': 'Containers-as-a-service (CaaS) is a type of cloud service in which the provider allows users to manage and install containerized apps and clusters. Containers are key here.', 'reference': 'Sumo Logic, Inc., “Containers-as-a-service (CaaS) - definition & overview,” Sumo Logic, Mar. 16, 2023. https://www.sumologic.com/glossary/caas/' },
  { 'id': 42, 'term': 'Load Balancer', 'description': 'A load balancer is a device that serves as a reverse proxy, distributing network or application traffic over many servers.  It is in charge of handling incoming traffic for a website and distributing it evenly. ', 'reference': '“What is a Load Balancer?,” F5. https://www.f5.com/glossary/load-balancer' },
  { 'id': 43, 'term': 'Cron Job', 'description': 'A CronJob generates Jobs on a regular basis. It is a scheduled process that will execute a specific script on a server at a specific time. ', 'reference': '“CronJob,” Kubernetes, Aug. 24, 2023. https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/' },
  { 'id': 44, 'term': 'RabbitMQ', 'description': 'RabbitMQ is an open-source message broker that aids in application scalability by implementing a message queuing mechanism between the two applications. ', 'reference': 'A. Jadon, “Understanding RabbitMQ Queue & Messaging Simplified 101,” Learn | Hevo, Dec. 2022, [Online]. Available: https://hevodata.com/learn/rabbitmq-queue/' },
  { 'id': 45, 'term': 'Bitbucket', 'description': 'BitBucket is a cloud-based service that allows developers to save and manage their code while also tracking and controlling changes to it.', 'reference': 'GeeksforGeeks, “Introduction to BitBucket,” GeeksforGeeks, May 2022, [Online]. Available: https://www.geeksforgeeks.org/introduction-to-bitbucket/' },
  { 'id': 46, 'term': 'Persistent Volume', 'description': 'A PersistentVolume (PV) is a piece of storage in a cluster that has been either manually provisioned by an administrator or dynamically created using Storage Classes. ', 'reference': '“Persistent volumes,” Kubernetes, Sep. 15, 2023. https://kubernetes.io/docs/concepts/storage/persistent-volumes/' },
  { 'id': 47, 'term': 'Fluentd', 'description': 'Fluentd is a cloud-native logging system that streamlines data gathering and consumption.', 'reference': '“Fluentd: Unified logging layer,” GitHub. https://github.com/fluent' },
  { 'id': 48, 'term': 'Elasticsearch', 'description': 'Elasticsearch is a distributed search and analytics engine that was designed for use cases such as log analytics, full-text search, security intelligence, business analytics, and operational intelligence.', 'reference': '“Elasticsearch: What is it and why it’s important - AWS,” Amazon Web Services, Inc. https://aws.amazon.com/what-is/elasticsearch/' },
  { 'id': 49, 'term': 'StatefulSet', 'description': 'The workload API object StatefulSet is used to manage stateful applications. It oversees the deployment and scaling of a collection of Pods.', 'reference': '“StatefulSets,” Kubernetes, Sep. 28, 2023. https://kubernetes.io/docs/concepts/workloads/controllers/statefulset' },
  { 'id': 50, 'term': 'Ingress', 'description': 'Ingress offers HTTP and HTTPS routes from outside the cluster to cluster services. The Ingress resource defines the rules that govern traffic routing.', 'reference': '“Ingress,” Kubernetes, Aug. 24, 2023. https://kubernetes.io/docs/concepts/services-networking/ingress/' }
]

/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', { title: 'SIT722', items: itemList });
});

module.exports = router;
