var express = require('express');
var router = express.Router();

const itemList = [
  { 'id': 1, 'term': 'DevOps', 'description': 'DevOps, which stands for development and operations, is a set of practices and technologies that aim to improve an organizations capacity to produce applications and services more quickly than traditional software development procedures. ', 'reference': '“What Is DevOps and How Does It Work? | Synopsys,” www.synopsys.com. https://www.synopsys.com/glossary/what-is-devops.html' },
  { 'id': 2, 'term': 'Continuous Integration', 'description': 'Continuous integration developers commit their code changes to a centralized repository on a regular basis, following which automated builds and tests are done.', 'reference': '“What is Continuous Integration? – Amazon Web Services,” Amazon Web Services, Inc. https://aws.amazon.com/devops/continuous-integration/' },
  { 'id': 3, 'term': 'Continuous Deployment', 'description': 'Continuous deployment is a completely developed and comprehensive code change process cycle that goes through every phase of the software life cycle before being delivered to production settings. Automated incremental changes are done as a part of this.', 'reference': 'S. Vadapalli, DevOps: Continuous Delivery, Integration, and Deployment with DevOps: Dive into the core DevOps strategies. Packt Publishing Ltd, 2018.' },
  { 'id': 4, 'term': 'Microservice', 'description': 'A microservice is a small, self-contained software operation that can be deployed and maintained independently.', 'reference': 'A. K. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform: A project-based guide. 2021. [Online]. Available: https://discovery.ebsco.com/linkprocessor/plink?id=db0e7980-bdfb-3d3b-b4e9-127c44a7aebb' },
  { 'id': 5, 'term': 'Shorter Lead Time', 'description': 'It is the time required to get from committing code to successfully executing code in production.', 'reference': 'D. DeBellis and C. Peters, “DORA 2022 Accelerate State of DevOps Report now out,” Google Cloud Blog, Sep. 28, 2022. https://cloud.google.com/blog/products/devops-sre/dora-2022-accelerate-state-of-devops-report-now-out' },
  { 'id': 6, 'term': 'Bootstrap', 'description': 'Bootstrap is the most widely used HTML, CSS, and JS framework for creating a responsive and mobile-friendly website. It can also utilise JavaScript plug-ins.', 'reference': '“What is Bootstrap.” https://www.w3schools.com/whatis/whatis_bootstrap.asp' },
  { 'id': 7, 'term': 'Docker', 'description': 'Docker is a tool that is used to package and publish microservices.', 'reference': 'A. K. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform: A project-based guide. 2021. [Online]. Available: https://discovery.ebsco.com/linkprocessor/plink?id=db0e7980-bdfb-3d3b-b4e9-127c44a7aebb' },
  { 'id': 8, 'term': 'Kubernetes', 'description': 'Kubernetes is a container-based application management platform. It can manage and automate container deployment and scaling. ', 'reference': 'A. K. Davis, Bootstrapping Microservices with Docker, Kubernetes, and Terraform: A project-based guide. 2021. [Online]. Available: https://discovery.ebsco.com/linkprocessor/plink?id=db0e7980-bdfb-3d3b-b4e9-127c44a7aebb' },
  { 'id': 9, 'term': 'Deployment Frequency', 'description': 'The frequency with which software is deployed in a company. ', 'reference': 'D. DeBellis and C. Peters, “DORA 2022 Accelerate State of DevOps Report now out,” Google Cloud Blog, Sep. 28, 2022. https://cloud.google.com/blog/products/devops-sre/dora-2022-accelerate-state-of-devops-report-now-out' },
  { 'id': 10, 'term': 'Recovery Time', 'description': 'The time it takes to repair a service or program that has malfunctioned or gone down. ', 'reference': 'D. DeBellis and C. Peters, “DORA 2022 Accelerate State of DevOps Report now out,” Google Cloud Blog, Sep. 28, 2022. https://cloud.google.com/blog/products/devops-sre/dora-2022-accelerate-state-of-devops-report-now-out' },
  { 'id': 11, 'term': 'Preprod', 'description': 'It is the process by which an organisation prepares the environment and infrastructure for each release by testing apps prior to deployment to production.  It simulates the production environment, where various features are tested before they are delivered to customers.', 'reference': 'Enov, “Preprod Done Right: the Definitive Guide,” Enov8, Feb. 2023, [Online]. Available: https://www.enov8.com/blog/preprod-done-right-the-definitive-guide/' },
  { 'id': 12, 'term': 'Source Code Management', 'description': 'It is a software that is used to track changes to a source code repository. It stores and tracks all the changes that are made to code, documents, etc.', 'reference': 'Atlassian, “Source Code Management | Atlassian Git Tutorial,” Atlassian. https://www.atlassian.com/git/tutorials/source-code-management' },
  { 'id': 13, 'term': 'DevSecOps', 'description': 'It stands for development, security, and operations. The notion of incorporating security practices into the DevOps process is known as DevSecOps. DevSecOps entails fostering a culture of Security as Code through continual, flexible cooperation between release engineers and security teams.', 'reference': '“What is DevSecOps?” https://www.redhat.com/en/topics/devops/what-is-devsecops' },
  { 'id': 14, 'term': 'Docker Image', 'description': 'It is a file which is used to execute code in a docker container.', 'reference': 'A. S. Gillis, “Docker image,” IT Operations, May 2021, [Online]. Available: https://www.techtarget.com/searchitoperations/definition/Docker-image' },
  { 'id': 15, 'term': 'Release Management', 'description': 'It is the process of planning, creating, scheduling, testing, delivering, and controlling software releases ', 'reference': '“What is Release Management? | OpenText.” https://www.microfocus.com/en-us/what-is/release-management' },
  { 'id': 16, 'term': 'Scrum', 'description': 'Scrum is an agile project management framework that uses a set of values, principles, and practises to help teams structure and manage their work. It employs time-boxed development cycles.', 'reference': 'Atlassian, “What is Scrum?,” Atlassian. [Online]. Available: https://www.atlassian.com/agile/scrum' },
  { 'id': 17, 'term': 'Acceptance Testing', 'description': 'Process for determining how well an application meets the approval of end users.', 'reference': 'Jeroen Mulder, Enterprise DevOps for Architects [e-book]. PacktPublishing,2021. Available:https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/' },
  { 'id': 18, 'term': 'Regression Testing', 'description': 'The testing of a software application to see if any recent modifications have had an unfavorable effect on any functionality that were previously in existence. ', 'reference': 'Jeroen Mulder, Enterprise DevOps for Architects [e-book]. PacktPublishing,2021. Available:https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/' },
  { 'id': 19, 'term': 'Agile', 'description': 'Agile project management is based on iterative and collaborative development.', 'reference': 'Coursera, “What is agile? and when to use it,” Coursera, Jul. 2023, [Online]. Available: https://www.coursera.org/articles/what-is-agile-a-beginners-guide' },
  { 'id': 20, 'term': 'Infrastructure as Code', 'description': 'Infrastructure as Code is a piece of code that is responsible for building linked cloud resources known as infrastructure on top of which an application may operate. IaC aids in the automated deployment of infrastructure. ', 'reference': 'Jeroen Mulder, Enterprise DevOps for Architects [e-book]. PacktPublishing,2021. Available:https://learning.oreilly.com/library/view/enterprise-devops-for/9781801812153/' }


]

/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', { title: 'SIT722', items: itemList });
});

module.exports = router;
